name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Vim
      run: sudo add-apt-repository -yu ppa:jonathonf/vim && sudo apt-get install -qq vim
    - name: Run tests
      run: make check
